<?php
// $Id$

/***
* EZAC leerling volgsysteem v7.x-1.0
* 
* Functie: administreren van vliegstandaard
* 
*/

/**
* Globals
*/

  global $datum_default;
  global $maand_default;
  global $jaar_default;
  global $download;
  
  $datum_default = ($datum_default == '') ? date('Y-m-d') : $datum_default;
  $maand_default = ($maand_default == '') ? date('Y-m') : $maand_default;
  $jaar_default  = ($jaar_default == '') ? date('Y') : $jaar_default;

/**
* Implementation of hook_permission().
*/
function ezaclvs_permission() {
  return array(
    'ezac_lvs_view' => array(
      'title' => t('EZAC LVS inzage'),
      'description' => t('Bekijken EZAC leerling volgsysteem.'),
    ),
    'ezac_lvs_input' => array(
      'title' => t('EZAC LVS invoer'),
      'description' => t('Invoer in EZAC leerling volgsysteem.'),
    ),
    'ezac_lvs_edit' => array(
      'title' => t('EZAC LVS wijziging'),
      'description' => t('Wijzigen in EZAC leerling volgsysteem.'),
    ),
  );
}

/**
* Implementation of hook_menu().
*/
function ezaclvs_menu() {
  //prepare dates for menu items
  $dag = date('Y-m-d');
  $maand = date('Y-m');
  $jaar = date('Y');
  //build menu
  $items = array();
    $items['lvs'] = array(
    'title' => 'Invoer verslag vliegdag',
    'description'=> 'Aanmaken dagverslag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_verslag_form'),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_NORMAL_ITEM
    ); 
  $items['lvs/verslag'] = array(
    'title' => 'Invoer verslag vliegdag',
    'description'=> 'Aanmaken dagverslag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_verslag_form'),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0, 
    );
  $items['lvs/persoon'] = array( 
    'title' => 'Invoer verslag persoon',
    'description'=> 'Verslag persoon',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_persoon_form', FALSE),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    );
  $items['lvs/overzicht'] = array(
      'title' => 'Overzicht persoon',
      'description'=> 'Overzicht bevoegdheden',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ezaclvs_persoon_form', TRUE),
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
    );
  $items['lvs/rapport'] = array(
      'title' => 'Rapport',
      'description'=> 'Rapportage LVS',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ezaclvs_rapport_form', TRUE),
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 3,
    );
  $items['lvs/tabel'] = array(
      'title' => 'Tabel',
      'description'=> 'Tabel invoer bevoegdheden LVS',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ezaclvs_tabel_form', TRUE),
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 4,
    );
  $items['lvs/download'] = array(
      'title' => 'Download',
      'description'=> 'Download a report',
      'page callback' => '_ezaclvs_download',
      'page arguments' => '',
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_CALLBACK,
    );

  return $items;
}


/** form theming starts here **/

/**
 * Implementation of hook_theme.
 */
function ezaclvs_theme() {
  return array(
    'ezaclvs_form_table' => array(
      // The renderable element is the form.
      'render element' => 'form',
    ),
  );
}


/**
 * Theme callback for the form table.
 */
function theme_ezaclvs_form_table(&$variables) {
    // Get the useful values.
    $form = $variables['form'];
    $rows = $form['rows'];
    $header = $form['#header'];

    // Setup the structure to be rendered and returned.
    $content = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => array(),
    );

    // Traverse each row.  @see element_chidren().
    foreach (element_children($rows) as $row_index) {
        $row = array();
        // Traverse each column in the row.  @see element_children().
        foreach (element_children($rows[$row_index]) as $col_index) {
            // Render the column form element.
            $row[] = drupal_render($rows[$row_index][$col_index]);
        }
    // Add the row to the table.
    $content['#rows'][] = $row;
    }

    // Render the table and return.
    return drupal_render($content);
}

/** form theming ends here **/

/**
 * Lees bevoegdheden in tabel
 * @returns array $bevoegdheden [bevoegdheid] = array(id, naam, status, instructeur)
 */
function ezaclvs_get_bevoegdheden() {
  $bevoegdheden = db_select('ezac_lvs_bevoegdheden', 'b')
                ->fields('b', array('id', 'bevoegdheid', 'naam', 'status', 'instructeur'))
                ->execute()->fetchAll();
  
  foreach ($bevoegdheden as $bevoegdheid) {
    $bevoegd[$bevoegdheid->bevoegdheid] = array(
        'id' => $bevoegdheid->id,
        'naam' => $bevoegdheid->naam,
        'status' => $bevoegdheid->status, //indicatie leerling status
        'instructeur' => $bevoegdheid->instructeur, //indicatie instructeur status
    );
  }
  return $bevoegd;
}

/**
* Build dagrapport form.
* @returns array $form renderable drupal form
*/
function ezaclvs_verslag_form($form = NULL, &$form_state) {

    global $jaar_default;
    global $datum_default;
    global $namen;
  
    //get afkorting for logged-in user
    $afkorting = ezac_get_afkorting();
                         
    $namen = ezac_get_namen();
    //$namen[''] = '<leeg>';
    //$namen['Onbekend'] = '<Onbekend>';
  
    // find this year's flight days, descending
    $query = db_select('ezac_starts', 's');
    $query->fields('s',array('datum'));
    $query->condition('s.datum', $jaar_default .'-01-01', '>'); 
    $query->distinct(); //unique values
    $query->orderBy('s.datum', 'DESC');
    $starts = $query->execute()->fetchAll();
    foreach ($starts as $start) {
        $start_dates[$start->datum] = ezac_show_date($start->datum); //list of dates for selection
    }
    $datum = key($start_dates); // most recent date value
    
    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = '<p><h2>Aanmaken dagverslag</h2></p>'; 
    $form['titel']['#weight'] = 0;
  
    // make most recent day active
    // present as default date in dropdown list
    $form['datum'] = array(
    '#title' => t('Datum'),
    //'#type' => 'date_popup', //extension to 'date'
    //'#date_format' => 'Y-m-d',
    //'#default_value' => $start['datum'],
    '#type' => 'select',
    '#options' => $start_dates,
    '#default_value' => $datum,  //most recent date
    //'#description' => t('Datum'),
    '#weight' => 1,
    '#ajax' => array(
        'callback' => 'ezaclvs_verslag_callback', 
        'wrapper' => 'vliegers-div',
        'effect' => 'fade',
        'progress' => array('type' => 'none'),
        ), 
    );
    
    // @TODO present tick box for alternative date with ajax date entry field

    // set instructeur default to value of current user
    // present drop list with leden
    $afkorting = ezac_get_afkorting();
    
  $form['instructeur'] = array(
    '#title' => t('Instructeur / verantwoordelijke'),
    '#type' => 'select',
    '#options' => $namen,  //@TODO select only instructeur from namen
    '#default_value' => $afkorting,
    //'#description' => t('Instructeur of verantwoordelijke'),
    '#weight' => 2,
  );
    
    // textaera field for 'weer' (2 lines)
  $form['weer'] = array(
    '#title' => t('Weer en baanrichting'),
    '#type' => 'textarea',
    '#rows' => 2,
    //'#default_value' => $verslag_waarde,
    '#weight' => 3,
    '#prefix' => '<div id="weer">',
    '#suffix' => '</div>',
  );
    // textarea field for 'verslag'  (10 lines)
  $form['verslag'] = array(
    '#title' => t('Algemeen verslag'),
    '#type' => 'textarea',
    '#rows' => 10,
    //'#default_value' => $verslag,
    '#required' => TRUE,  
    '#weight' => 4,
    '#prefix' => '<div id="verslag">',
    '#suffix' => '</div>',
  );
    
    // generate form element with vliegers for the selected day
    // get starts->gezagvoerder, starts->tweede in $namen
    $datum_form = !empty($form_state['values']['datum']) 
                   ? $form_state['values']['datum'] 
                   : $datum;
    $query = db_select('ezac_starts', 's');
    $query->fields('s',array('gezagvoerder', 'tweede'));
    $query->condition('s.datum', $datum_form, '='); 
    $starts = $query->execute()->fetchAll();

    $vliegers = array(); 
    foreach ($starts as $start) {
        // @TODO filter for instructie starts (disregard gezagvoerder - instructeur)
        $gezagvoerder = $start->gezagvoerder;
        if (!isset($vliegers[$gezagvoerder])) 
            $vliegers[$gezagvoerder] = $namen[$gezagvoerder];
        if (isset($start->tweede) && ($start->tweede <>'')) {
            $tweede = $start->tweede;
            if (!isset($vliegers[$tweede])) 
                $vliegers[$tweede] = $namen[$tweede];
        }
    }

    //[vliegers] form wordt door AJAX opnieuw opgebouwd
    $form['vliegers'] = array(
    '#title' => t('Opmerkingen per vlieger'),
    '#type' => 'container',
    '#weight' => 5,
    '#prefix' => '<div id="vliegers-div">', //This section replaced by AJAX callback
    '#suffix' => '</div>',
    '#tree' => TRUE,
    );
    
    //Toon eerdere verslagen per lid
    foreach ($vliegers as $afkorting => $helenaam) {
        // query lvs verslag, bevoegdheid records
        // @TODO NOG UIT TE WERKEN
        $query = db_select('ezac_lvs_dagverslagen_lid', 'l');
        $query->fields('l', array('id', 'afkorting', 'instructeur', 'datum', 'verslag'));
        $query->condition('afkorting', $afkorting, '=');
        $verslagen = $query->execute()->fetchAll();
        //dpm($verslagen, 'verslagen'); //debug
        // put in table
    
        if (!empty($verslagen)) { //create fieldset
            $form['vliegers'][$afkorting]['verslagen'] = array(
                '#title' => t("Eerdere verslagen voor $helenaam"),
                '#type'=> 'fieldset',
                '#edit' => FALSE,
                '#required' => FALSE,
                '#collapsible' => TRUE,
                '#collapsed' => TRUE,
                '#weight' => 5,
                '#tree' => TRUE,
                );
            }

        foreach ($verslagen as $verslag) {
            //show as markup in form or textfield with edit=false
            $form['vliegers'][$afkorting]['verslagen'][$verslag->id] = array(
                '#title' => $verslag->datum,
                '#markup' => '<p>' .ezac_show_date($verslag->datum) .' - '
                .'Instructeur: ' .$namen[$verslag->instructeur] 
                .'<br>' .$verslag->verslag //@TODO format with line breaks 
                .'</p>',
                '#tree' => TRUE,
                '#weight' => 5,
            );
        }    
    }
    
    //  list with persons who have flown that day - each may be selected
    //   enter persoon_verslag 
    //   possible entry of 'bevoegdheid' as of datum 
    
    // @TODO SORT $vliegers
    foreach ($vliegers as $afkorting => $helenaam) {

    // invoeren opmerking
    $form['vliegers'][$afkorting]['opmerking'] = array(
        '#title' => t("Opmerkingen voor $helenaam"),
        '#type' => 'textarea',
        '#rows' => 3,
        '#required' => FALSE,  
        '#weight' => 5,
        '#tree' => TRUE,
    );
    // invoeren bevoegdheid - nested container with verslag / bevoegdheid?
    // alternative is a button jumping to add bevoegdheid form
        //$form['vliegers'][$naam]['bevoegdheid'] = array();
        // @TODO select from drop list with known bevoegdheid values
    }
   
    //submit
    $form['submit'] = array(
    '#type' => 'submit',
    '#description' => t('Verslag opslaan en via mail verzenden'),
    '#value' => t('Opslaan'),
    '#weight' => 99,
    );

  return $form;
}

/**
 * Selects the piece of the form we want to use as replacement text and returns
 * it as a form (renderable array).
 *
 * @return renderable array (the textfields element)
 */
function ezaclvs_verslag_callback($form, $form_state) {
    return $form['vliegers']; //HTML for verslag form['vliegers']
}


/**
* Validate the form.
*/
function ezaclvs_verslag_form_validate($form, &$form_state) {
  if (!isset($form_state['values'])) return;

    //dpm($form, 'form validate'); //debug
    //dpm($form_state,'form_state validate'); //debug
    
  //datum
  $dc = explode('-', $form_state['values']['datum']);
  if (!checkdate($dc[1], $dc[2], $dc[0])) form_set_error('datum', 'ongeldige datum');

  
  //confirm delete bij op == Verwijderen
  if (isset($form_state['values']['op'])) {
    if (($form_state['values']['op'] == 'Verwijderen') && ($form_state['values']['verwijderen'] == 0)) {
      form_set_error('verwijderen', 'Selecteer Verwijderen én druk op de knop Verwijderen om deze vlucht te ...');
      return;
    }
  }
}

/**
* Handle post-validation form submission.
*/
function ezaclvs_verslag_form_submit($form, &$form_state) {
  global $namen;
  global $current_url;
  
    $datum = $form_state['values']['datum'];
    $instructeur = $form_state['values']['instructeur'];
    $weer = $form_state['values']['weer'];
    $verslag = $form_state['values']['verslag'];
    $op = $form_state['values']['op'];
    
    //write verslag to ezac_LVS_verslag
    if ($form_state['values']['weer'].$form_state['values']['verslag'] <> '') {
        $id = db_insert('ezac_LVS_Dagverslagen')
        ->fields(array(
            'datum' => $form_state['values']['datum'],
            'instructeur' => $form_state['values']['instructeur'],
            'weer' => $form_state['values']['weer'],
            'verslag' => $form_state['values']['verslag'],
        ))
        ->execute();
        drupal_set_message('Dagverslag voor ' .ezac_show_date($form_state['values']['datum']) .' aangemaakt', 'status');
    }
    //write verslag per vlieger
    foreach ($form_state['values']['vliegers'] as $afkorting => $verslag) {
        if ($verslag <> '') {
        $id = db_insert('ezac_LVS_dagverslagen_lid')
            ->fields(array(
                'datum' => $form_state['values']['datum'],
                'afkorting' => $afkorting,
                'instructeur' => $form_state['values']['instructeur'],
                'verslag' => $verslag['opmerking'],
            ))
            ->execute();
            //drupal_set_message('Verslag voor ' .$namen[$afkorting] .' aangemaakt', 'status');
        }
    }
    
  // return result
  
  //redirect naar calling url
  if ($current_url != "") {
    $form_state['redirect'] = $current_url;
  }
  else $form_state['redirect'] = 'lvs';
  return;
}


/**
* Build persoon form.
* Show current bevoegdheid and verslag info
* Enter opmerking and/or bevoegdheid when $overzicht == FALSE
* @param array $form
* @param array &$form_state
* @param boolean $overzicht FALSE: enter details, TRUE: overzicht
* @returns array $form renderable drupal form
*/
function ezaclvs_persoon_form($form, &$form_state, $overzicht = FALSE) {
    
    global $namen;
    global $bevoegdheden;
    $namen = ezac_get_namen();
    
    //instructeur  is logged-in user
    //get afkorting for logged-in user
    $afkorting = ezac_get_afkorting();

    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = '<p><h2>Opmerkingen en bevoegdheden</h2></p>'; 
    $form['titel']['#weight'] = 0;

    if (!$overzicht) {
        // make most recent day active
        // present as default date in dropdown list
        $form['datum'] = array(
        '#title' => t('Datum'),
        '#type' => 'date_popup', //extension to 'date'
        '#date_format' => 'Y-m-d',
        '#default_value' => date('Y-m-d'),
        '#weight' => 1,
        );

        // set instructeur default to value of current user
        // present drop list with leden
    
        $form['instructeur'] = array(
        '#title' => t('Instructeur'),
        '#type' => 'select',
        '#options' => $namen,  //@TODO select only instructeur from namen
        '#default_value' => $afkorting,
        '#weight' => 2,
        );
    }
    
    //@TODO select time period for overzicht
    
    //select person
    $form['persoon'] = array(
    '#title' => t('Vlieger'),
    '#type' => 'select',
    '#options' => $namen, 
    //'#default_value' => key($namen),
    '#weight' => 3,
    '#ajax' => array(
        'callback' => 'ezaclvs_verslag_callback', 
        'wrapper' => 'vliegers-div',
        'effect' => 'fade',
        'progress' => array('type' => 'none'),
        ), 
    );

    //[vliegers] form wordt door AJAX opnieuw opgebouwd
    $form['vliegers'] = array(
    '#title' => t('Vlieger'),
    '#type' => 'container',
    '#weight' => 4,
    '#prefix' => '<div id="vliegers-div">', //This section replaced by AJAX callback
    '#suffix' => '</div>',
    '#tree' => TRUE,
    );

    $vlieger_afkorting = (isset($form_state['values']['persoon']) && ($form_state['values']['persoon'] <> ''))
    ? $form_state['values']['persoon']
    : key($namen); //top value as default
    $helenaam = $namen[$vlieger_afkorting];
    
    $datum = (isset($form_state['values']['datum']) && ($form_state['values']['datum'] <> ''))
    ? $form_state['values']['datum']
    : date('Y-m-d'); //today as default

    //toon vluchten dit jaar
    $form['vliegers']['starts'] = ezacstart_browse(date('Y'), $vlieger_afkorting, TOTALS);
    
    if (!$overzicht) {
        // invoeren opmerking
        $form['vliegers']['opmerking'] = array(
            '#title' => t("Opmerkingen voor $helenaam"),
            '#type' => 'textarea',
            '#rows' => 3,
            '#required' => FALSE,  
            '#weight' => 5,
            '#tree' => TRUE,
        );
    }
    
    //Toon eerdere verslagen per lid
    // query lvs verslag, bevoegdheid records
    $query = db_select('ezac_lvs_dagverslagen_lid', 'l');
    $query->fields('l', array('id', 'afkorting', 'instructeur', 'datum', 'verslag'));
    $query->condition('afkorting', $vlieger_afkorting, '=');
    $verslagen = $query->execute()->fetchAll();

    // put in table
    if (!empty($verslagen)) { //create fieldset
        $form['vliegers']['verslagen'][$vlieger_afkorting] = array(
            '#title' => t("Eerdere verslagen voor $helenaam"),
            '#type'=> 'fieldset',
            '#edit' => FALSE,
            '#required' => FALSE,
            '#collapsible' => TRUE,
            '#collapsed' => !$overzicht,
            '#weight' => 6,
            '#tree' => TRUE,
            );
        }

    foreach ($verslagen as $verslag) {
        //show as markup in form or textfield with edit=false
        $form['vliegers']['verslagen'][$vlieger_afkorting][$verslag->id] = array(
            '#title' => $verslag->datum,
            '#markup' => '<p>' .ezac_show_date($verslag->datum) .' - '
            .'Instructeur: ' .$namen[$verslag->instructeur] 
            .'<br>' .$verslag->verslag //@TODO format with line breaks 
            .'</p>',
            '#tree' => TRUE,
            '#weight' => 6,
        );
    }    
    
    $bevoegdheden = ezaclvs_get_bevoegdheden();
    $bv_list[0] = '<Geen wijziging>';
    if (isset($bevoegdheden)) {
        foreach ($bevoegdheden as $bevoegdheid => $bevoegdheid_array) {
            $bv_list[$bevoegdheid] = $bevoegdheid_array['naam'];
        }
    }
    //toon huidige bevoegdheden
    // query lvs verslag, bevoegdheid records
    // @TODO JOIN ezac_lvs_bevoegdheden bevoegdheid naam
    $query = db_select('ezac_lvs_bevoegdheid_lid', 'b');
    $query->fields('b', array('id', 'afkorting', 'instructeur', 'datum_aan', 'bevoegdheid', 'actief', 'onderdeel', 'opmerking'));
    $query->condition('afkorting', $vlieger_afkorting, '=');
    $query->condition('actief', TRUE, '=');
    $vlieger_bevoegdheden = $query->execute()->fetchAll();
    // put in table
    
    if (!empty($vlieger_bevoegdheden)) { //create fieldset
        $form['vliegers']['bevoegdheden'][$vlieger_afkorting] = array(
            '#title' => t("Bevoegdheden voor $helenaam"),
            '#type'=> 'fieldset',
            '#edit' => FALSE,
            '#required' => FALSE,
            '#collapsible' => TRUE,
            '#collapsed' => !$overzicht,
            '#weight' => 7,
            '#tree' => TRUE,
            );
        }

    foreach ($vlieger_bevoegdheden as $bevoegdheid) {
        //show as markup in form or textfield with edit=false
        $form['vliegers']['bevoegdheden'][$vlieger_afkorting][$bevoegdheid->id] = array(
            '#title' => $bevoegdheid->datum_aan,
            '#markup' => '<p>' .ezac_show_date($bevoegdheid->datum_aan) .' - '
            .'Instructeur: ' .$namen[$bevoegdheid->instructeur] 
            .'<br>' .$bevoegdheid->bevoegdheid .' - '
            .$bv_list[$bevoegdheid->bevoegdheid] .' '
            .$bevoegdheid->onderdeel . ' '
            .$bevoegdheid->opmerking
            .'</p>',
            '#tree' => TRUE,
            '#weight' => 7,
        );
    }    
    
    if (!$overzicht) {
        //invoer bevoegdheid
        $form['bevoegdheid'] = array(
        '#title' => 'Bevoegdheid',
        '#type' => 'container',
        '#prefix' => '<div id="bevoegdheid-div">',
        '#suffix' => '</div>',
        '#required' => FALSE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#weight' => 10,
        '#tree' => TRUE,
        );

        $form['bevoegdheid']['keuze'] = array(
        '#title' => t('Bevoegdheid'),
        '#type' => 'select',
        '#options' => $bv_list,
        '#default_value' => 0, //<Geen wijziging>
        '#weight' => 10,
        '#tree' => TRUE,
        '#ajax' => array(
            'callback' => 'ezaclvs_bevoegdheid_callback', 
            'wrapper' => 'bevoegdheid-div',
            'effect' => 'fade',
            'progress' => array('type' => 'none'),
            ), 
        );

        //@TODO het onderstaande if blok werkt niet.
        if (isset($form_state['values']['bevoegdheid']['keuze']) 
            && ($form_state['values']['bevoegdheid']['keuze'] <> '0')) { 

            $form['bevoegdheid']['onderdeel'] = array(
            '#title' => t('Onderdeel'),
            '#description' => 'Bijvoorbeeld overland type',
            '#type' => 'textfield',
            '#required' => FALSE,
            '#default_value' => '',
            '#weight' => 11,
            '#tree' => TRUE,
            );
         }

        //submit
        $form['submit'] = array(
        '#type' => 'submit',
        '#description' => t('Opslaan'),
        '#value' => t('Opslaan'),
        '#weight' => 99,
        );
    }

  return $form;
}

/**
 * Selects the piece of the form we want to use as replacement text and returns
 * it as a form (renderable array).
 *
 * @return renderable array (the textfields element)
 */
function ezaclvs_bevoegdheid_callback($form, $form_state) {
    return $form['bevoegdheid'];
}

function ezaclvs_persoon_form_validate($form, &$form_state) {
    //@TODO verify that bevoegdheid is not given earlier
}
    
function ezaclvs_persoon_form_submit ($form, &$form_state) {
    global $bevoegdheden;
    
    if ($form_state['values']['vliegers']['opmerking'] <> '') {
        $id = db_insert('ezac_LVS_dagverslagen_lid')
            ->fields(array(
                'datum' =>      $form_state['values']['datum'],
                'afkorting' =>  $form_state['values']['persoon'],
                'instructeur' => $form_state['values']['instructeur'],
                'verslag' =>    $form_state['values']['vliegers']['opmerking'],
            ))
            ->execute();
        drupal_set_message('Verslag aangemaakt', 'status');
    }
    
    
    if ($form_state['values']['bevoegdheid']['keuze'] <> '0') {
        $id = db_insert('ezac_LVS_bevoegdheid_lid')
            ->fields(array(
                'datum_aan' => $form_state['values']['datum'],
                'afkorting' =>  $form_state['values']['persoon'],
                'instructeur' => $form_state['values']['instructeur'],
                'bevoegdheid' => $form_state['values']['bevoegdheid']['keuze'],
                'actief' => TRUE,
                'onderdeel' => isset($form_state['values']['bevoegdheid']['onderdeel'])
                    ? $form_state['values']['bevoegdheid']['onderdeel']
                    : '',
            ))
            ->execute();
        
        $status = db_select('ezac_lvs_bevoegdheden', 'b')
            ->condition('b.bevoegdheid', $form_state['values']['bevoegdheid']['keuze'], '=')
            ->fields('b', array('status'))
            ->execute()->fetchField();

        switch ($status)  { //change leerling and instructie status
            case '1':   $num_updated = db_update('ezac_leden') //DBO
                                     ->fields(array('leerling' => 1))
                                     ->condition('afkorting', $form_state['values']['persoon'], '=')
                                     ->execute();
                        break;
            case '2':   $num_updated = db_update('ezac_leden') //SOLO
                                     ->fields(array('leerling' => 1))
                                     ->condition('afkorting', $form_state['values']['persoon'], '=')
                                     ->execute();
                        break;
            case '3':   $num_updated = db_update('ezac_leden') //GPL
                                     ->fields(array('leerling' => 0))
                                     ->condition('afkorting', $form_state['values']['persoon'], '=')
                                     ->execute();
                        break;
            case '4':   $num_updated = db_update('ezac_leden') //Instructeur
                                     ->fields(array('instructie' => 1))
                                     ->condition('afkorting', $form_state['values']['persoon'], '=')
                                     ->execute();
                        break;
            case '5':   $num_updated = db_update('ezac_leden') //Examinator
                                     ->fields(array('instructie' => 1))
                                     ->condition('afkorting', $form_state['values']['persoon'], '=')
                                     ->execute();
                        break;
        }
        $hoogste_bevoegdheid = db_select('ezac_leden', 'l')
            ->condition('l.afkorting', $form_state['values']['persoon'], '=')
            ->fields('l', array('bevoegdheid'))
            ->execute()->fetchfield();
        if ($status > $hoogste_bevoegdheid) {
            $num_updated = db_update('ezac_leden') //update bevoegdheid
                ->fields(array('bevoegdheid' => $status))
                ->condition('afkorting', $form_state['values']['persoon'], '=')
                ->execute();
        }
        drupal_set_message('Bevoegdheid aangemaakt', 'status');
    }

    return;
}

/**
* Build rapport form.
* Een DBO-er lijst, solisten lijst, een VVO-1 lijst en GPL-er lijst met aantal vluchten over te kiezen periode
* @returns array $form renderable drupal form
*/
function ezaclvs_rapport_form($form, &$form_state) {
    // form header info

    $bevoegdheden = ezaclvs_get_bevoegdheden();
    foreach ($bevoegdheden as $bevoegdheid => $bevoegdheid_array) {
        //@TODO verwijder bevoegdheden met status=0 uit de lijst?
        $lijst[$bevoegdheid] = $bevoegdheid_array['naam'];
    }
    
    //@TODO make $datum selectable (range)
    $datum = date('Y'); //this year

    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = "<p><h2>Rapportage Leerling volgsysteem $datum</h2></p>"; 
    $form['titel']['#weight'] = 0;

    // select report category: DBO, solist, VVO, GPL
    $form['selectie'] = array(
        '#type' => 'select',
        '#title' => t('Selectie'),
        //'#default_value' => isset($selectie) ? $selectie : 1,
        '#options' => $lijst,
        '#description' => t('Selecteer de categorie voor het overzicht'),
        '#ajax' => array(
            'callback' => 'ezaclvs_rapport_callback', 
            'wrapper' => 'rapport-div',
            'effect' => 'fade',
            'progress' => array('type' => 'none'),
        ),
    );
    
    $form['rapport'] = array(
        '#title' => t("Rapportage"),
        '#type'=> 'container',
        '#prefix' => '<div id="rapport-div">',
        '#suffix' => '</div>',
        //'#edit' => FALSE,
        '#required' => FALSE,
        '#weight' => 1,
        '#tree' => TRUE,
    );
    
    //create report
    
    $selectie = (isset($form_state['values']['selectie']))
        ? $form_state['values']['selectie']
        : key($lijst);

    // select target group from ezac_leden
    $leden = array();

    $query = db_select('ezac_leden', 'l');
    $query->join('ezac_lvs_bevoegdheid_lid', 'bl', 'l.afkorting = bl.afkorting');
    $leden = $query->fields('l', array('afkorting'))
            ->fields('bl', array('bevoegdheid'))
            ->condition('l.actief', 1)
            //geen hogere bevoegdheid dan geselecteerde
            ->condition('l.bevoegdheid', $bevoegdheden[$selectie]['status'], '<=') 
            ->condition('bl.bevoegdheid', $selectie, '=')
            ->execute()->fetchAllKeyed(0, 1);

    // build report details
    // use report function from ezacstart module
    $form['rapport']['overzicht'] = ezacstart_report_table($datum, $leden);
    $form['rapport']['overzicht']['#tree'] = TRUE;
    //$form['rapport']['overzicht']['#weight'] = 3;

    return $form;
}

function ezaclvs_rapport_callback($form, $form_state) {
    return $form['rapport'];
}

/**
* Build tabel form.
* Enter or change bevoegdheid for any leden record
* @param array $form
* @param array &$form_state
* @returns array $form renderable drupal form
*/
function ezaclvs_tabel_form($form, &$form_state) {
    
    global $namen;
    global $bevoegdheden;
    global $bl;

    //read namen from ezac_leden VL records
    $namen = ezac_get_namen();

    //read bevoegdheden definitions
    $bevoegdheden = ezaclvs_get_bevoegdheden();
    
    //instructeur  is logged-in user
    //get afkorting for logged-in user
    $afkorting = ezac_get_afkorting();

    //prepare form header
    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = '<p><h2>Tabel invoer bevoegdheden</h2></p>'; 
    $form['titel']['#weight'] = 0;

    // set instructeur default to value of current user
    // present drop list with leden

    $form['instructeur'] = array(
    '#title' => t('Instructeur'),
    '#type' => 'select',
    '#options' => $namen,  //@TODO select only instructeur from namen
    '#default_value' => $afkorting,
    '#weight' => 2,
    );

    // query lvs verslag, bevoegdheid records
    $bevoegdheden_leden = db_select('ezac_lvs_bevoegdheid_lid', 'bl')
        ->fields('bl', array('afkorting', 'id', 'instructeur', 'datum_aan', 
                            'bevoegdheid', 'actief', 'onderdeel', 'opmerking'))
        //->condition('afkorting', $vlieger_afkorting, '=')
        ->condition('actief', TRUE, '=')
        ->execute()->fetchAll(); //Assoc('afkorting');
    //build array $bl(afkorting, bevoegdheid) = array(datum, id)
    foreach ($bevoegdheden_leden as $bevoegdheid) {
        $bl[$bevoegdheid->afkorting][$bevoegdheid->bevoegdheid]['datum'] = $bevoegdheid->datum_aan;
        $bl[$bevoegdheid->afkorting][$bevoegdheid->bevoegdheid]['id'] = $bevoegdheid->id;
    }
    //build table form
    $header = array('Naam');
    foreach ($bevoegdheden as $bevoegdheid => $bevoegdheid_array) {
        array_push($header, $bevoegdheid);
    }

    //build rows array of column arrays
    $rows = array(
        '#tree' => TRUE,
    );
    $row_nr = 0; //for cell index in form table
    $namen_lijst = array(); //initialize namen lijst for validate and submit
    foreach ($namen as $afkorting => $naam) {
        // build row with bevoegdheid values
        $row_nr++; //next row
        $namen_lijst[] = array(
            'afkorting' => $afkorting,
            'naam' => $naam,
        );
        //Start the row with the Naam
        $row_value = array(
                array(
                    '#type' => 'markup',
                    '#markup' => $naam,
                    '#size' => 25,
                    '#sticky' => TRUE, //this doesn't work
                ),
        );
        $col_nr = 0; //for cell index in form table
        foreach ($bevoegdheden as $bevoegdheid => $bevoegdheid_array) {
            //create datum entry field for this $bevoegdheid for this $afkorting (person)
            $col_nr++; //next column
            $rc_value = (isset($bl[$afkorting][$bevoegdheid])) 
                       ? $bl[$afkorting][$bevoegdheid]['datum'] 
                       : '';                
            array_push($row_value, array(
                    '#type' => 'textfield',
                    //'#title' => $bevoegdheid,
                    '#maxlength' => 10,
                    '#size' => 10,
                    '#default_value' => $rc_value,
                )
            );
        }
        array_push($rows, $row_value);
    }
    //show table with datum entry field for each bevoegdheid record per naam
    $form['table'] = array(
    // Theme this part of the form as a table.
    '#theme' => 'ezaclvs_form_table',
    '#header' => $header,
    '#weight' => 5,
    // Rows in the form table.
    'rows' => $rows,
    );
    
    $form['bevoegdheden'] = array(
    '#type' => 'value',
    '#value' => $header, //store header info for bevoegdheid reference in submit
    );
    
    $form['namen'] = array(
    '#type' => 'value',
    '#value' => $namen_lijst,
    );
    
    $form['submit'] = array(
    '#type' => 'submit',
    '#description' => t('Aanpassen van de bevoegdheden'),
    '#value' => t('Invoeren'),
    '#weight' => 99,
    );
    
    return $form;
} //ezaclvs_tabel

function ezaclvs_tabel_form_validate($form, &$form_state) {
    //validate all form[rows] elements for correct date function
    $bevoegdheden = $form_state['values']['bevoegdheden']; //from table header
    $namen = $form_state['values']['namen']; // namen[] = array(afkorting, naam)
    foreach ($form_state['values']['rows'] as $r => $row) {
        foreach($row as $c => $bev_datum) {
            //index 1 => bevoegdheid[1] 
            if (!empty($bev_datum)) {
                $lv = explode('-',$bev_datum);
                if (!checkdate($lv[1],$lv[2],$lv[0])) { //month, day, year
                    $naam = $namen[$r]['naam'];
                    form_set_error("rows][$r][$c","Ongeldige datum $bev_datum bij $naam voor $bevoegdheden[$c] [YYYY-MM-DD]");
                } //datum fout
            } //datum
        } //column
    } //row
}

function ezaclvs_tabel_form_submit($form, &$form_state) {
    //check all table fields for change against bevoegdhedeid_lid value
    //update or enter records accordingly
    global $bl; //bevoegdheden leden
    //global $namen; //leden afkorting => helenaam
    $bevoegdheden = $form_state['values']['bevoegdheden']; //from table header
    $namen = $form_state['values']['namen']; // namen[] = array(afkorting, naam)
    
    foreach ($form_state['values']['rows'] as $r => $row) {
        foreach($row as $c => $bev_datum) {
            //index 1 => bevoegdheid[1] 
            if (!empty($bev_datum)) {
                //check of datum is gewijzigd
                $afkorting = $namen[$r]['afkorting'];
                $naam = $namen[$r]['naam'];
                $bevoegdheid = $bevoegdheden[$c];
                if (isset($bl[$afkorting]) 
                    && isset($bl[$afkorting][$bevoegdheid]) 
                    && $bl[$afkorting][$bevoegdheid]['datum'] <> $bev_datum) {
                    if (!empty($bl[$afkorting][$bevoegdheid]['datum'])) { //datum is gewijzigd: update record
                        $num_updated = db_update('ezac_lvs_bevoegdheid_lid')
                            ->condition('id', $bl[$afkorting][$bevoegdheid]['id'])
                            ->fields(array(
                                'afkorting' => $afkorting,
                                'bevoegdheid' => $bevoegdheid,
                                'instructeur' => $form_state['values']['instructeur'],
                                'datum_aan' => $bev_datum,
                                'actief' => TRUE,
                                ))
                             ->execute();
                        if ($num_updated) {
                            drupal_set_message("Bevoegdheid $bevoegdheid voor $naam aangepast met datum $bev_datum");
                        }
                    } //datum gewijzigd
                } // nog geen bevoegdheid geregistreerd?
                else { //datum is nieuw ingevuld: insert record
                    if (!isset($bl[$afkorting])
                        || !isset($bl[$afkorting][$bevoegdheid])) { //nog geen bevoegdheid voor deze afkorting
                        $id = db_insert('ezac_lvs_bevoegdheid_lid')
                            ->fields(array(
                                'afkorting' => $afkorting,
                                'bevoegdheid' => $bevoegdheid,
                                'instructeur' => $form_state['values']['instructeur'],
                                'datum_aan' => $bev_datum,
                                'actief' => TRUE,
                                ))
                             ->execute();
                        if (isset($id)) {
                            drupal_set_message("Bevoegdheid $bevoegdheid voor $naam aangemaakt met datum $bev_datum");
                        }
                    }
                } // datum nieuw ingevuld
            } //datum ingevuld
        } //column
    } //row
}
