<?php
// $Id$

/***
* EZAC leerling volgsysteem v7.x-1.0
* 
* Functie: administreren van vliegstandaard
* 
*/

/**
* Globals
*/

  global $datum_default;
  global $maand_default;
  global $jaar_default;
  global $download;
  
  $datum_default = ($datum_default == '') ? date('Y-m-d') : $datum_default;
  $maand_default = ($maand_default == '') ? date('Y-m') : $maand_default;
  $jaar_default  = ($jaar_default == '') ? date('Y') : $jaar_default;

/**
* Implementation of hook_permission().
*/
function ezaclvs_permission() {
  return array(
    'ezac_lvs_view' => array(
      'title' => t('EZAC LVS inzage'),
      'description' => t('Bekijken EZAC leerling volgsysteem.'),
    ),
    'ezac_lvs_input' => array(
      'title' => t('EZAC LVS invoer'),
      'description' => t('Invoer in EZAC leerling volgsysteem.'),
    ),
    'ezac_lvs_edit' => array(
      'title' => t('EZAC LVS wijziging'),
      'description' => t('Wijzigen in EZAC leerling volgsysteem.'),
    ),
  );
}

/**
* Implementation of hook_menu().
*/
function ezaclvs_menu() {
  //prepare dates for menu items
  $dag = date('Y-m-d');
  $maand = date('Y-m');
  $jaar = date('Y');
  //build menu
  $items = array();
    $items['lvs'] = array(
    'title' => 'EZAC verslag',
    'description'=> 'Aanmaken dagverslag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_verslag_form'),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_NORMAL_ITEM
    ); 
  $items['lvs/verslag'] = array(
    'title' => 'Verslag vliegdag',
    'description'=> 'Aanmaken dagverslag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_verslag_form'),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0, 
    );
  $items['lvs/persoon'] = array( 
    'title' => 'Verslag voor persoon',
    'description'=> 'Verslag voor persoon',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_persoon_form', FALSE),
    'access callback' => 'user_access',
    'access arguments' => array('ezac_lvs_input'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    );
  $items['lvs/overzicht'] = array(
      'title' => 'Overzicht',
      'description'=> 'Overzicht bevoegdheden',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezaclvs_persoon_form', TRUE),
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
    );
  $items['lvs/download'] = array(
      'title' => 'Download',
      'description'=> 'Download a report',
      'page callback' => '_ezaclvs_download',
      'page arguments' => '',
      'access callback' => 'user_access',
      'access arguments' => array('ezac_lvs_input'),
      'type' => MENU_CALLBACK,
    );

  return $items;
}


/**
 * Lees bevoegdheden in tabel
 * @returns array $bevoegdheden [id] = array(bevoegdheid, naam, leerling, instructeur)
 */
function ezaclvs_get_bevoegdheden() {
  $query = db_select('ezac_lvs_bevoegdheden', 'b');
  $query->fields('b', array('id', 'bevoegdheid', 'naam', 'status', 'instructeur'));
  $bevoegdheden = $query->execute()->fetchAll();
  
  foreach ($bevoegdheden as $bevoegdheid) {
    $bevoegd[$bevoegdheid->id] = array(
        'bevoegdheid' => $bevoegdheid->bevoegdheid,
        'naam' => $bevoegdheid->naam,
        'status' => $bevoegdheid->status, //indicatie leerling status
        'instructeur' => $bevoegdheid->instructeur, //indicatie instructeur status
    );
  }
  return $bevoegd;
}

/**
* Build dagrapport form.
* @returns array $form renderable drupal form
*/
function ezaclvs_verslag_form($form = NULL, &$form_state) {

    global $jaar_default;
    global $datum_default;
    global $namen;
  
    //get afkorting for logged-in user
    $afkorting = ezac_get_afkorting();
                         
    $namen = ezac_get_namen();
    //$namen[''] = '<leeg>';
    //$namen['Onbekend'] = '<Onbekend>';
  
    // find this year's flight days, descending
    $query = db_select('ezac_starts', 's');
    $query->fields('s',array('datum'));
    $query->condition('s.datum', $jaar_default .'-01-01', '>'); 
    $query->distinct(); //unique values
    $query->orderBy('s.datum', 'DESC');
    $starts = $query->execute()->fetchAll();
    foreach ($starts as $start) {
        $start_dates[$start->datum] = ezac_show_date($start->datum); //list of dates for selection
    }
    $datum = key($start_dates); // most recent date value
    
    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = '<p><h2>Aanmaken dagverslag</h2></p>'; 
    $form['titel']['#weight'] = 0;
  
    // make most recent day active
    // present as default date in dropdown list
    $form['datum'] = array(
    '#title' => t('Datum'),
    //'#type' => 'date_popup', //extension to 'date'
    //'#date_format' => 'Y-m-d',
    //'#default_value' => $start['datum'],
    '#type' => 'select',
    '#options' => $start_dates,
    '#default_value' => $datum,  //most recent date
    //'#description' => t('Datum'),
    '#weight' => 1,
    '#ajax' => array(
        'callback' => 'ezaclvs_verslag_callback', 
        'wrapper' => 'vliegers-div',
        'effect' => 'fade',
        'progress' => array('type' => 'none'),
        ), 
    );
    
    // @TODO present tick box for alternative date with ajax date entry field

    // set instructeur default to value of current user
    // present drop list with leden
    $afkorting = ezac_get_afkorting();
    
  $form['instructeur'] = array(
    '#title' => t('Instructeur / verantwoordelijke'),
    '#type' => 'select',
    '#options' => $namen,  //@TODO select only instructeur from namen
    '#default_value' => $afkorting,
    //'#description' => t('Instructeur of verantwoordelijke'),
    '#weight' => 2,
  );
    
    // textaera field for 'weer' (2 lines)
  $form['weer'] = array(
    '#title' => t('Weer en baanrichting'),
    '#type' => 'textarea',
    '#rows' => 2,
    //'#default_value' => $verslag_waarde,
    '#weight' => 3,
    '#prefix' => '<div id="weer">',
    '#suffix' => '</div>',
  );
    // textarea field for 'verslag'  (10 lines)
  $form['verslag'] = array(
    '#title' => t('Algemeen verslag'),
    '#type' => 'textarea',
    '#rows' => 10,
    //'#default_value' => $verslag,
    '#required' => TRUE,  
    '#weight' => 4,
    '#prefix' => '<div id="verslag">',
    '#suffix' => '</div>',
  );
    
    // generate form element with vliegers for the selected day
    // get starts->gezagvoerder, starts->tweede in $namen
    $datum_form = !empty($form_state['values']['datum']) 
                   ? $form_state['values']['datum'] 
                   : $datum;
    $query = db_select('ezac_starts', 's');
    $query->fields('s',array('gezagvoerder', 'tweede'));
    $query->condition('s.datum', $datum_form, '='); 
    $starts = $query->execute()->fetchAll();

    $vliegers = array(); 
    foreach ($starts as $start) {
        // @TODO filter for instructie starts (disregard gezagvoerder - instructeur)
        $gezagvoerder = $start->gezagvoerder;
        if (!isset($vliegers[$gezagvoerder])) 
            $vliegers[$gezagvoerder] = $namen[$gezagvoerder];
        if (isset($start->tweede) && ($start->tweede <>'')) {
            $tweede = $start->tweede;
            if (!isset($vliegers[$tweede])) 
                $vliegers[$tweede] = $namen[$tweede];
        }
    }

    //[vliegers] form wordt door AJAX opnieuw opgebouwd
    $form['vliegers'] = array(
    '#title' => t('Opmerkingen per vlieger'),
    '#type' => 'container',
    '#weight' => 5,
    '#prefix' => '<div id="vliegers-div">', //This section replaced by AJAX callback
    '#suffix' => '</div>',
    '#tree' => TRUE,
    );
    
    //Toon eerdere verslagen per lid
    foreach ($vliegers as $afkorting => $helenaam) {
        // query lvs verslag, bevoegdheid records
        // @TODO NOG UIT TE WERKEN
        $query = db_select('ezac_lvs_dagverslagen_lid', 'l');
        $query->fields('l', array('id', 'afkorting', 'instructeur', 'datum', 'verslag'));
        $query->condition('afkorting', $afkorting, '=');
        $verslagen = $query->execute()->fetchAll();
        //dpm($verslagen, 'verslagen'); //debug
        // put in table
    
        if (!empty($verslagen)) { //create fieldset
            $form['vliegers'][$afkorting]['verslagen'] = array(
                '#title' => t("Eerdere verslagen voor $helenaam"),
                '#type'=> 'fieldset',
                '#edit' => FALSE,
                '#required' => FALSE,
                '#collapsible' => TRUE,
                '#collapsed' => TRUE,
                '#weight' => 5,
                '#tree' => TRUE,
                );
            }

        foreach ($verslagen as $verslag) {
            //show as markup in form or textfield with edit=false
            $form['vliegers'][$afkorting]['verslagen'][$verslag->id] = array(
                '#title' => $verslag->datum,
                '#markup' => '<p>' .ezac_show_date($verslag->datum) .' - '
                .'Instructeur: ' .$namen[$verslag->instructeur] 
                .'<br>' .$verslag->verslag //@TODO format with line breaks 
                .'</p>',
                '#tree' => TRUE,
                '#weight' => 5,
            );
        }    
    }
    
    //  list with persons who have flown that day - each may be selected
    //   enter persoon_verslag 
    //   possible entry of 'bevoegdheid' as of datum 
    
    // @TODO SORT $vliegers
    foreach ($vliegers as $afkorting => $helenaam) {

    // invoeren opmerking
    $form['vliegers'][$afkorting]['opmerking'] = array(
        '#title' => t("Opmerkingen voor $helenaam"),
        '#type' => 'textarea',
        '#rows' => 3,
        '#required' => FALSE,  
        '#weight' => 5,
        '#tree' => TRUE,
    );
    // invoeren bevoegdheid - nested container with verslag / bevoegdheid?
    // alternative is a button jumping to add bevoegdheid form
        //$form['vliegers'][$naam]['bevoegdheid'] = array();
        // @TODO select from drop list with known bevoegdheid values
    }
   
    //submit
    $form['submit'] = array(
    '#type' => 'submit',
    '#description' => t('Verslag opslaan en via mail verzenden'),
    '#value' => t('Opslaan'),
    '#weight' => 99,
    );

  return $form;
}

/**
 * Selects the piece of the form we want to use as replacement text and returns
 * it as a form (renderable array).
 *
 * @return renderable array (the textfields element)
 */
function ezaclvs_verslag_callback($form, $form_state) {
    return $form['vliegers']; //HTML for verslag form['vliegers']
    //return $form;
}


/**
* Validate the form.
*/
function ezaclvs_verslag_form_validate($form, &$form_state) {
  if (!isset($form_state['values'])) return;

    //dpm($form, 'form validate'); //debug
    //dpm($form_state,'form_state validate'); //debug
    
  //datum
  $dc = explode('-', $form_state['values']['datum']);
  if (!checkdate($dc[1], $dc[2], $dc[0])) form_set_error('datum', 'ongeldige datum');

  
  //confirm delete bij op == Verwijderen
  if (isset($form_state['values']['op'])) {
    if (($form_state['values']['op'] == 'Verwijderen') && ($form_state['values']['verwijderen'] == 0)) {
      form_set_error('verwijderen', 'Selecteer Verwijderen én druk op de knop Verwijderen om deze vlucht te ...');
      return;
    }
  }
}

/**
* Handle post-validation form submission.
*/
function ezaclvs_verslag_form_submit($form, &$form_state) {
  global $namen;
  global $current_url;
  
    $datum = $form_state['values']['datum'];
    $instructeur = $form_state['values']['instructeur'];
    $weer = $form_state['values']['weer'];
    $verslag = $form_state['values']['verslag'];
    $op = $form_state['values']['op'];
    
    //write verslag to ezac_LVS_verslag
    if ($form_state['values']['weer'].$form_state['values']['verslag'] <> '') {
        $id = db_insert('ezac_LVS_Dagverslagen')
        ->fields(array(
            'datum' => $form_state['values']['datum'],
            'instructeur' => $form_state['values']['instructeur'],
            'weer' => $form_state['values']['weer'],
            'verslag' => $form_state['values']['verslag'],
        ))
        ->execute();
        drupal_set_message('Dagverslag voor ' .ezac_show_date($form_state['values']['datum']) .' aangemaakt', 'status');
    }
    //write verslag per vlieger
    foreach ($form_state['values']['vliegers'] as $afkorting => $verslag) {
        if ($verslag <> '') {
        $id = db_insert('ezac_LVS_dagverslagen_lid')
            ->fields(array(
                'datum' => $form_state['values']['datum'],
                'afkorting' => $afkorting,
                'instructeur' => $form_state['values']['instructeur'],
                'verslag' => $verslag['opmerking'],
            ))
            ->execute();
            //drupal_set_message('Verslag voor ' .$namen[$afkorting] .' aangemaakt', 'status');
        }
    }
    
  // return result
  
  //redirect naar calling url
  if ($current_url != "") {
    $form_state['redirect'] = $current_url;
  }
  else $form_state['redirect'] = 'lvs';
  return;
}


/**
* Build persoon form.
* Show current bevoegdheid and verslag info
* Enter opmerking and/or bevoegdheid when $overzicht == FALSE
* @param array $form
* @param array &$form_state
* @param boolean $overzicht
* @returns array $form renderable drupal form
*/
function ezaclvs_persoon_form($form, &$form_state, $overzicht = FALSE) {
    
    global $namen;
    $namen = ezac_get_namen();
    
    //instructeur  is logged-in user
    //get afkorting for logged-in user
    $afkorting = ezac_get_afkorting();

    $form['titel']['#type'] = 'markup';
    $form['titel']['#markup'] = '<p><h2>Opmerkingen en bevoegdheden</h2></p>'; 
    $form['titel']['#weight'] = 0;

    if (!$overzicht) {
        // make most recent day active
        // present as default date in dropdown list
        $form['datum'] = array(
        '#title' => t('Datum'),
        '#type' => 'date_popup', //extension to 'date'
        '#date_format' => 'Y-m-d',
        '#default_value' => date('Y-m-d'),
        '#weight' => 1,
        );

        // set instructeur default to value of current user
        // present drop list with leden
    
        $form['instructeur'] = array(
        '#title' => t('Instructeur'),
        '#type' => 'select',
        '#options' => $namen,  //@TODO select only instructeur from namen
        '#default_value' => $afkorting,
        '#weight' => 2,
        );
    }
    
    //select person
    $form['persoon'] = array(
    '#title' => t('Vlieger'),
    '#type' => 'select',
    '#options' => $namen, 
    //'#default_value' => key($namen),
    '#weight' => 3,
    '#ajax' => array(
        'callback' => 'ezaclvs_verslag_callback', 
        'wrapper' => 'vliegers-div',
        'effect' => 'fade',
        'progress' => array('type' => 'none'),
        ), 
    );

    //[vliegers] form wordt door AJAX opnieuw opgebouwd
    $form['vliegers'] = array(
    '#title' => t('Vlieger'),
    '#type' => 'container',
    '#weight' => 4,
    '#prefix' => '<div id="vliegers-div">', //This section replaced by AJAX callback
    '#suffix' => '</div>',
    '#tree' => TRUE,
    );

    $vlieger_afkorting = (isset($form_state['values']['persoon']) && ($form_state['values']['persoon'] <> ''))
    ? $form_state['values']['persoon']
    : key($namen); //top value as default
    $helenaam = $namen[$vlieger_afkorting];
    
    if (!$overzicht) {
        // invoeren opmerking
        $form['vliegers']['opmerking'] = array(
            '#title' => t("Opmerkingen voor $helenaam"),
            '#type' => 'textarea',
            '#rows' => 3,
            '#required' => FALSE,  
            '#weight' => 5,
            '#tree' => TRUE,
        );
    }
    
    //Toon eerdere verslagen per lid
    // query lvs verslag, bevoegdheid records
    $query = db_select('ezac_lvs_dagverslagen_lid', 'l');
    $query->fields('l', array('id', 'afkorting', 'instructeur', 'datum', 'verslag'));
    $query->condition('afkorting', $vlieger_afkorting, '=');
    $verslagen = $query->execute()->fetchAll();
    // put in table
    
    if (!empty($verslagen)) { //create fieldset
        $form['vliegers']['verslagen'][$vlieger_afkorting] = array(
            '#title' => t("Eerdere verslagen voor $helenaam"),
            '#type'=> 'fieldset',
            '#edit' => FALSE,
            '#required' => FALSE,
            '#collapsible' => TRUE,
            '#collapsed' => !$overzicht,
            '#weight' => 6,
            '#tree' => TRUE,
            );
        }

    foreach ($verslagen as $verslag) {
        //show as markup in form or textfield with edit=false
        $form['vliegers']['verslagen'][$vlieger_afkorting][$verslag->id] = array(
            '#title' => $verslag->datum,
            '#markup' => '<p>' .ezac_show_date($verslag->datum) .' - '
            .'Instructeur: ' .$namen[$verslag->instructeur] 
            .'<br>' .$verslag->verslag //@TODO format with line breaks 
            .'</p>',
            '#tree' => TRUE,
            '#weight' => 6,
        );
    }    
    
    $bevoegdheden = ezaclvs_get_bevoegdheden();
    $bv_list[0] = '<Geen wijziging>';
    if (isset($bevoegdheden)) {
        foreach ($bevoegdheden as $id => $bevoegdheid) {
            $bv_list[$bevoegdheid['bevoegdheid']] = $bevoegdheid['naam'];
        }
    }
    //toon huidige bevoegdheden
    // query lvs verslag, bevoegdheid records
    // @TODO JOIN ezac_lvs_bevoegdheden bevoegdheid naam
    $query = db_select('ezac_lvs_bevoegdheid_lid', 'b');
    $query->fields('b', array('id', 'afkorting', 'instructeur', 'datum_aan', 'bevoegdheid', 'actief', 'onderdeel', 'opmerking'));
    $query->condition('afkorting', $vlieger_afkorting, '=');
    $query->condition('actief', TRUE, '=');
    $bevoegdheden = $query->execute()->fetchAll();
    // put in table
    
    if (!empty($bevoegdheden)) { //create fieldset
        $form['vliegers']['bevoegdheden'][$vlieger_afkorting] = array(
            '#title' => t("Bevoegdheden voor $helenaam"),
            '#type'=> 'fieldset',
            '#edit' => FALSE,
            '#required' => FALSE,
            '#collapsible' => TRUE,
            '#collapsed' => !$overzicht,
            '#weight' => 7,
            '#tree' => TRUE,
            );
        }

    foreach ($bevoegdheden as $bevoegdheid) {
        //show as markup in form or textfield with edit=false
        $form['vliegers']['bevoegdheden'][$vlieger_afkorting][$bevoegdheid->id] = array(
            '#title' => $bevoegdheid->datum_aan,
            '#markup' => '<p>' .ezac_show_date($bevoegdheid->datum_aan) .' - '
            .'Instructeur: ' .$namen[$bevoegdheid->instructeur] 
            .'<br>' .$bevoegdheid->bevoegdheid .' - '
            .$bv_list[$bevoegdheid->bevoegdheid] .' '
            .$bevoegdheid->onderdeel . ' '
            .$bevoegdheid->opmerking
            .'</p>',
            '#tree' => TRUE,
            '#weight' => 7,
        );
    }    
    
    if (!$overzicht) {
        //invoer bevoegdheid
        $form['bevoegdheid'] = array(
        '#title' => 'Bevoegdheid',
        '#type' => 'container',
        '#prefix' => '</div id="bevoegdheid-div">',
        '#suffix' => '</div>',
        '#required' => FALSE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#weight' => 10,
        '#tree' => TRUE,
        );

        $form['bevoegdheid']['keuze'] = array(
        '#title' => t('Bevoegdheid'),
        '#type' => 'select',
        '#options' => $bv_list,
        '#default_value' => 0, //<Geen wijziging>
        '#weight' => 10,
        '#tree' => TRUE,
        '#ajax' => array(
            'callback' => 'ezaclvs_bevoegdheid_callback', 
            'wrapper' => 'bevoegdheid-div',
            'effect' => 'fade',
            'progress' => array('type' => 'none'),
            ), 
        );

        if (isset($form_state['values']['bevoegdheid']['keuze']) 
            && ($form_state['values']['bevoegdheid']['keuze'] <> '0')) { 

            $form['bevoegdheid']['onderdeel'] = array(
            '#title' => t('Onderdeel'),
            '#description' => 'Bijvoorbeeld overland type',
            '#type' => 'textfield',
            '#required' => FALSE,
            '#default_value' => '',
            '#weight' => 11,
            '#tree' => TRUE,
            );
         }

        //submit
        $form['submit'] = array(
        '#type' => 'submit',
        '#description' => t('Opslaan'),
        '#value' => t('Opslaan'),
        '#weight' => 99,
        );
    }

  return $form;
}

/**
* genereer form onderdeel met huidige bevoegdheden en verslagen
* returns array $form
*/
function ezaclvs_huidig() {

    return $form;
}

/**
 * Selects the piece of the form we want to use as replacement text and returns
 * it as a form (renderable array).
 *
 * @return renderable array (the textfields element)
 */
function ezaclvs_bevoegdheid_callback($form, $form_state) {
    return $form['bevoegdheid'];
}

function ezaclvs_persoon_form_validate($form, &$form_state) {
}
    
function ezaclvs_persoon_form_submit ($form, &$form_state) {
    
    if ($form_state['values']['vliegers']['opmerking'] <> '') {
        $id = db_insert('ezac_LVS_dagverslagen_lid')
            ->fields(array(
                'datum' =>      $form_state['values']['datum'],
                'afkorting' =>  $form_state['values']['persoon'],
                'instructeur' => $form_state['values']['instructeur'],
                'verslag' =>    $form_state['values']['vliegers']['opmerking'],
            ))
            ->execute();
        drupal_set_message('Verslag aangemaakt', 'status');
    }
    
    
    if ($form_state['values']['bevoegdheid']['keuze'] <> '0') {
        $id = db_insert('ezac_LVS_bevoegdheid_lid')
            ->fields(array(
                'datum_aan' => $form_state['values']['datum'],
                'afkorting' =>  $form_state['values']['persoon'],
                'instructeur' => $form_state['values']['instructeur'],
                'bevoegdheid' => $form_state['values']['bevoegdheid']['keuze'],
                'actief' => TRUE,
                'onderdeel' => isset($form_state['values']['bevoegdheid']['onderdeel'])
                    ? $form_state['values']['bevoegdheid']['onderdeel']
                    : '',
            ))
            ->execute();
        drupal_set_message('Bevoegdheid aangemaakt', 'status');
    
    }
    //dpm($form_state, 'form_state submit'); //debug
    return;
}

/**
* Build overzicht form.
* Show opmerking and/or bevoegdheid
* @returns array $form renderable drupal form
*/
function ezaclvs_overzicht_form($form, &$form_state) {
    
}