<?php
// $Id$

/**
*  ezacwebcam module
*  Management of the webcam at the EZAC location
*  webcam view: (bestuurbaar) live view beeld
*  webcam manage: bekijken en verwijderen van opgeslagen bewakingsfoto's
*/

/**
* Implementation of hook_permission().
*/
function ezacwebcam_permission() {
  return array(
    'webcam_view' => array(
      'title' => t('EZAC webcam bekijken'),
      'description' => t('Bekijken webcam beeld.'),
    ),
    'webcam_control' => array(
      'title' => t('EZAC webcam besturen'),
      'description' => t('Besturen webcam positie.'),
    ),
    'webcam_manage' => array(
      'title' => t('EZAC webcam foto beheer'),
      'description' => t('Beheren opgeslagen foto\'s.'),
    ),
  );
}
/**
* Implementation of hook_menu().
*/
function ezacwebcam_menu() {
$items = array();

	$items['webcam'] = array(
	  'title' => 'EZAC webcam',
	  'description'=> 'Beeld van de EZAC webcam',
	  'page callback' => 'ezacwebcam_page',
	  'page arguments' => '',
	  'type' => MENU_NORMAL_ITEM,
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_view')
	);
	$items['webcam/java'] = array(
	  'title'=> 'Java versie',
	  'page callback' => 'ezacwebcam_java',
	  'page arguments' => '',
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_view'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 1
	);
	$items['webcam/view'] = array(
	  'title' => 'Bekijken',
	  'page callback' => 'ezacwebcam_page',
	  'access callback' => 'user_access',
	  'access arguments' => array('webcam_view'),
          'type' => MENU_DEFAULT_LOCAL_TASK,
          'weight' => 0
	);
	$items['webcam/view/1'] = array(
	  'title'=> 'Deur',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position1'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 1
	);
	$items['webcam/view/2'] = array(
	  'title'=> 'Oost',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position2'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
	  'weight' => 2
	);
	$items['webcam/view/3'] = array(
	  'title'=> 'ZO',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position3'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 3
	);
	$items['webcam/view/4'] = array(
	  'title'=> 'Zuid',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position4'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 4
	);
	$items['webcam/view/5'] = array(
	  'title'=> 'ZZW',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position5'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
	  'weight' => 5
	);
	$items['webcam/view/6'] = array(
	  'title'=> 'ZW',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position6'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 6
	);
	$items['webcam/view/7'] = array(
	  'title'=> 'West',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position7'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 7
	);
	$items['webcam/view/8'] = array(
	  'title'=> 'Terras',
	  'page callback' => 'ezacwebcam_position',
	  'page arguments' => array('Position8'),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_control'),
 	  'type' => MENU_LOCAL_TASK,
          'weight' => 8
	);
    $items['webcam/manage'] = array(
	  'title' => 'Beheren',
	  'page callback' => 'ezacwebcam_manage_page',
	  'page arguments' => '',
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_manage'),
 	  'type' => MENU_LOCAL_TASK,
	  'weight' => 2
	);
    $items['webcam/manage/dir'] = array(
	  'title' => 'Beheren',
	  'page callback' => 'ezacwebcam_manage_page',
	  'page arguments' => array(2),
	  'access callback' => 'user_access',
          'access arguments' => array('webcam_manage'),
 	  'type' => MENU_CALLBACK
	);

return $items;
}
/**
* called to prepare file list from webcam directory
*/
function filecollect($cid,$dir='.') {
  static $flist=array();
  if ($files = ftp_nlist($cid,$dir)){
    foreach ($files as $file) {
      if (ftp_size($cid, $file) == "-1"){
        filecollect($cid,$file);
      } else {
	  list($webcam, $dir, $filename) = explode("/",$file);
	  $flist[$dir][] = $file;
	  }
    }
  }
  return $flist;
}

function ezacwebcam_java() {
$output = '';
$output .= '<object ';
$output .= ' classid = "clsid:CAFEEFAC-0015-0000-0012-ABCDEFFEDCBA"';
$output .= ' codebase = "http://java.sun.com/update/1.5.0/jinstall-1_5_0_12-windows-i586.cab#Version=5,0,120,4"';
$output .= ' WIDTH = "640" HEIGHT = "480" NAME = "ucx" >';
$output .= ' <PARAM NAME = CODE VALUE = "ultracam.class" >';
$output .= ' <PARAM NAME = ARCHIVE VALUE = "ultracam.jar" >';
$output .= ' <PARAM NAME = NAME VALUE = "ucx" >';
$output .= ' <param name = "type" value = "application/x-java-applet;jpi-version=1.5.0_12">';
$output .= ' <param name = "scriptable" value = "false">';
//$output .= ' <PARAM NAME = "accountcode" VALUE="YWRtaW46c29sb2s4" />';
$output .= ' <PARAM NAME = "accountcode" VALUE="ZXphYzp3ZWJtZXphYw" />'; //ezac/webmezac
$output .= ' <PARAM NAME = "codebase" VALUE="http://ezac.dyndns.org:8080/users" />';
$output .= ' <PARAM NAME = "mode" VALUE="0" />'; 
$output .= ' <comment>';
$output .= ' <embed ';
$output .= ' type = "application/x-java-applet" \\ ';
$output .= ' CODE = "ultracam.class" \\ ';
$output .= ' ARCHIVE = "ultracam.jar" \\ ';
$output .= ' NAME = "ucx" \\';
$output .= ' WIDTH = "640" \\';
$output .= ' HEIGHT = "480" \\';
$output .= ' accountcode ="YWRtaW46c29sb2s4" // \\';
$output .= ' codebase ="http://ezac.dyndns.org:8080/users" // \\';
$output .= ' mode ="0" // \\';
$output .= ' scriptable = false';
$output .= ' pluginspage = "http://java.sun.com/products/plugin/index.html#download">';
$output .= ' <noembed>  </noembed>';
$output .= '</embed> </comment> </object>';

return $output;
} //ezacwebcam_java

/**
* Called when user goes to example.com/?q=ledenlijst
*/
function ezacwebcam_page() {
// Return a java object to show the live webcam image
$output = 'Geen beeld? Kies dan "Java versie" (nodig voor Internet Explorer)<p>';
$output .= '<img src="http://ezac:webmezac@ezac.dyndns.org:8080/cgi/mjpg/mjpg.cgi"><p>';
//$output .= 'Image<p>';
//$output .= '<img src="http://ezac:webmezac@ezac.dyndns.org:8080/cgi/jpg/image.cgi"><p>';
return $output;
//return  ezacwebcam(image);
} //ezacwebcam_page

function ezacwebcam_position($Position) {
//select a webcam position
  $output = '<OBJECT DATA="http://ezacpos:mPvw=127@ezac.dyndns.org:8080/cgi/admin/ptctrl.cgi?action=move&Cmd='.$Position .'"';
  $output .= 'WIDTH="0" HEIGHT="0" TYPE="text/html">';
  $output .= 'Positie keuze niet beschikbaar</OBJECT><p>';
  $output .= '<img src="http://ezac:webmezac@ezac.dyndns.org:8080/cgi/mjpg/mjpg.cgi"><p>';
return $output;
}

/**
* Called when user goes to example.com/?q=ledenlijst
*/
function ezacwebcam_manage_page() {
// Return the HTML generated from the $form data structure.
//$output = drupal_get_form('ezacwebcam_view_form');
//return $output;

$dir = "webcam";
$output = '';
$conn_id = ftp_connect('efekkes.dyndns.org') or die("Couldn't connect to server");
  if (@ftp_login($conn_id, 'webcam', 'ezacwebcam')){
    ftp_pasv($conn_id, TRUE); //Passive Mode is better for this
    $filelist = filecollect($conn_id, $dir);
    foreach($filelist as $dirlist) {
      $file = $dirlist[0];
      list($webcam, $dir, $filename) = explode("/",$file);
      $output.= "[" .$dir ."] " .count($dirlist) ."<br>";
      $output .= "<img src='ftp://webcam:ezacwebcam@efekkes.dyndns.org/" .$file ."' width=120><br>";
      foreach($dirlist as $file) {
	  }
  //    echo "<img src='ftp://webcam:ezacwebcam@efekkes.dyndns.org/" .$file ."' width=40>";
    }
  }
//$attributes['width'] = '100';
//return theme('image',$path, $alt = '', $title = '', $attributes, $getsize = FALSE);
return $output;
}

/*
function ezacwebcam_manage_page() {
$output = drupal_get_form('ezacwebcam_manage_form');
return $output;
}
*/




/**
* Control the webcam movement
*/
function ezacwebcam_control_page() {
	return 'Deze functie is nog niet gebouwd';
	
} //ezacwebcam_control_page



